### ISSUE TITLE
Segment x Line intersection

### ISSUE THREAD

**Issue by manuel-delverme** [jan-mue/geometer#39] opened 2021-03-10 18:47 UTC
```
left_edge = geometer.Point(-1, 0.1)
right_edge = geometer.Point(1, 0.1)
line = geometer.Line(right_edge, left_edge)
segment = geometer.Segment(right_edge, left_edge)
circle = geometer.Conic(np.diag([1, 1, -0.01]))
point = geometer.Point(0, 0.9)

polar_line = circle.polar(point)
polar_points = circle.intersect(polar_line)

ray = geometer.Line(polar_points[0], point)
x_1 = ray.meet(line)
x_2 = ray.meet(segment)
```

I would expect the intersection between `line` and `ray` to be the same as `segment` and `ray` as the ray intersects the segment.

What am I doing wrong?

**Comment by jan-mue** [comment] 2021-03-21 15:58
The intersection between `line` and `ray` is the same as the intersection of `segment` and `ray`. The problem is that `meet` doesn't support passing an instance of type `Segment` as argument. You have to use `segment.intersect(ray)[0]` instead. The index `0` is needed because the `intersect` method returns a list of points.
I will close this issue but feel free to comment here if you need more help.

**Closed by jan-mue** 2021-03-21 15:58 UTC
